// var meterjson = {
//   "AllowedUnit":0,
// "Ampere:"10/30",
// "ApplyDate":null,
// "AutoPay":"false,
// "AvageUseUnit":99,
// "BillNeedModity":false,
// "BinderId":5,
// "Block":null,
// "BranchId":"1",
// "BusinessNo":"",
// "CategoryId":1,
// "CategoryName":"ရိုးရိုး",
// "ChargePerUnit":35,
// "ConsumerName":"ဦးအိုက်နပ်",
// "ConsumerType":"P",
// "CoverSeal":null,
// "CreditAmount":79040,
// "CreditReason":null,
// "CreditUnit":0,
// "CurrencyType":"ks",
// "CustomerId":"7324392739",
// "DueDate":November 17, 2021 at 12:00:00 AM UTC+6:30,
// "ExcelFileName":null,
// "FeederID":3,
// "GroupId":2,
// "HorsePower":0,
// "HorsePowerCost":0,
// "HouseNo":"အမှတ်-၂၀/၂၂၊ တက္ကသိုလ်ရိပ်သာလမ်း",
// "Id":2,
// "InsertDate":November 17, 2021 at 12:00:00 AM UTC+6:30,
// "InstallPerson":null,
// "IsShowDebt":
// true,
// "IssueDate":
// null,
// "JoinDate":
// November 17, 2021 at 12:00:00 AM UTC+6:30,
// "LastDate":
// November 17, 2021 at 12:00:00 AM UTC+6:30,
// "LastMonthRedUnit":
// null,
// "LastReadUnit":
// 13151,
// "Latitude":
// "22.9534015",
// "LayerAmount":
// null,
// "LayerDescription":
// null,
// "LayerRate":
// null,
// "LedgerId":
// "BH1",
// "LedgerPostFix":
// "01/03",
// "Longitude":
// "97.7405598",
// "MainLedgerId":
// 1,
// "MainLedgerTitle":
// "2110",
// "MaintainenceCost":
// 500,
// "ManufacturerNo":
// "10/30",
// "MeterNo":
// "YA-046496",
// "MeterSerial":
// "",
// "Mobile":
// "09123456789",
// "Multiplier":
// "1",
// "NoLayer":
// false,
// "NoOfRoom":
// 1,
// "OldAccount":
// null,
// "OutDemand":
// null,
// "Percentage":
// 0,
// "PoleNo":
// null,
// "Rate":
// "1 ",
// "ReadDate":
// November 18, 2021 at 12:00:00 AM UTC+6:30,
// "RequiredMatchGPS":
// false,
// "Street":
// "နယ်မြေ(၁)",
// "StreetLightCost":
// null,
// "TerminalSeal":
// null,
// "TransformerID":
// 49,
// "TspEng":
// null,
// "TspMM":
// null,
// "TwinLeftSeal":
// null,
// "TwinRightSeal":
// null,
// "Voltage":
// "230",
// "WattLoad":
// "",
// "meterBill":
// 150000,
// "meterName":
// "Home"};
